"""Diagnostic visual authoring modes for the vegetative skinning backend.

These helpers deliberately reuse the exact same smooth tube geometry generated by
``mesh.build_axis_tube_data`` while changing only how that geometry is attached to
USD.  They are used to isolate the cost of UsdSkel from the cost of the mesh itself.
"""

from pxr import Gf, UsdGeom, Vt

from .mesh import _axis_color, build_axis_tube_data
from .model import VisualAxisData


def _author_plain_mesh(
    stage,
    mesh_path: str,
    axis: VisualAxisData,
    points,
    face_counts,
    face_indices,
) -> None:
    """Author a non-skinned mesh with the same topology/color as the normal tube."""
    mesh = UsdGeom.Mesh.Define(stage, mesh_path)
    mesh.CreatePointsAttr().Set(Vt.Vec3fArray(points))
    mesh.CreateFaceVertexCountsAttr().Set(Vt.IntArray(face_counts))
    mesh.CreateFaceVertexIndicesAttr().Set(Vt.IntArray(face_indices))
    mesh.CreateSubdivisionSchemeAttr().Set(UsdGeom.Tokens.none)
    mesh.CreateOrientationAttr().Set(UsdGeom.Tokens.rightHanded)
    mesh.CreateDoubleSidedAttr().Set(True)
    mesh.CreateDisplayColorAttr().Set(Vt.Vec3fArray([
        Gf.Vec3f(*_axis_color(axis))
    ]))


def author_static_visual_axis(stage, axis: VisualAxisData) -> None:
    """Author the exact smooth tube as a static world-space mesh, with no UsdSkel.

    This is a pure performance diagnostic: physics continues to move, while this
    visual remains in its authored rest pose.  If this mode is fast, the mesh
    itself is not the main bottleneck and UsdSkel evaluation is implicated.
    """
    UsdGeom.Xform.Define(stage, axis.visual_root_path)
    points, face_counts, face_indices, _, _ = build_axis_tube_data(axis)
    _author_plain_mesh(
        stage,
        f"{axis.visual_root_path}/StaticMesh",
        axis,
        points,
        face_counts,
        face_indices,
    )


def author_rigid_visual_axis(stage, axis: VisualAxisData) -> None:
    """Attach a one-bone tube directly below its single PhysX rigid link.

    A visual axis driven by exactly one rigid link cannot deform internally, so a
    Skeleton/SkelAnimation adds no visual capability.  Parenting the mesh below
    the rigid link produces the same rigid motion without any UsdSkel evaluation
    or per-frame Python synchronization for that axis.
    """
    if len(axis.link_paths) != 1:
        raise ValueError(
            f"Rigid visual axis '{axis.axis_id}' must have exactly one physics link"
        )

    world_points, face_counts, face_indices, _, _ = build_axis_tube_data(axis)

    rest_world = Gf.Matrix4d(1.0)
    rest_world.SetTransform(
        Gf.Rotation(Gf.Quatd(axis.link_orientations[0])),
        axis.link_bases[0],
    )
    world_to_link = rest_world.GetInverse()

    local_points = [
        Gf.Vec3f(*world_to_link.Transform(Gf.Vec3d(*point)))
        for point in world_points
    ]

    _author_plain_mesh(
        stage,
        f"{axis.link_paths[0]}/VisualMesh",
        axis,
        local_points,
        face_counts,
        face_indices,
    )
